This may be a mess

diff --git a/.github/workflows/validate_prerelease.yml b/.github/workflows/validate_prerelease.yml
--- a/.github/workflows/validate_prerelease.yml
+++ b/.github/workflows/validate_prerelease.yml
@@ -4,7 +4,7 @@ on:
     types: [prereleased]
 
 jobs:
-  download_prerelease_assets:
+  count_prerelease_assets:
     name: Download Latest Pre-Release Assets
     runs-on: ubuntu-latest
     steps:
@@ -33,3 +33,43 @@ jobs:
             echo "::error::Expected 3 files, but found $FILE_COUNT"
             exit 1
           fi
+
+  validate_prerelease_x86_package:
+    name: Download, Install, and Validate Homebridge Package
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download release asset
+        id: download_release
+        uses: robinraju/release-downloader@v1.11
+        with:
+          fileName: 'homebridge_v1.3.10_amd64.deb'
+      
+      - name: List downloaded files
+        run: |
+          echo "Downloaded files:"
+          ls -l
+
+      - name: Install the downloaded package
+        run: |
+          sudo dpkg -i homebridge_v1.3.10_amd64.deb || sudo apt-get install -f -y
+
+      - name: Validate Homebridge Installation
+        run: |
+          homebridge --version
+
+      - name: Start and Validate Homebridge Service
+        run: |
+          homebridge &
+          sleep 10
+          sudo hb-service status
+          if pgrep -x "homebridge" > /dev/null; then
+            echo "::info::Homebridge is running successfully."
+          else
+            echo "::error::Homebridge failed to start."
+            exit 1
+          fi
+
+      - name: Stop Homebridge Service
+        run: |
+          pkill -f homebridge
+          
